# Week 7 Day 3: Feature Engineering Basics

---
## Internship Details

**Intern Name:** Dinesh Singh Dhami  
**Semester:** BE Computer 8th Semester  
**Company:** Sipalaya Info Tech, Kathmandu-32, Koteshwor  
**Domain:** Data Science  
**Task:** Feature Engineering Basics  
**Tools Used:** Python, Pandas, NumPy, Jupyter Notebook  

---

## Objective

The objective of this task is to learn feature engineering techniques by creating new meaningful features from existing columns in the housing dataset. Feature engineering helps improve model performance and data understanding.

## 6-Hour Daily Workflow

**Hour 1:** Study feature engineering concepts  
**Hour 2:** Understand existing dataset features  
**Hour 3:** Create new numerical features  
**Hour 4:** Create category-based features  
**Hour 5:** Create binary features  
**Hour 6:** Final dataset review, save dataset, documentation

### Import Libraries

In [1]:
import pandas as pd
import numpy as np

### Load Dataset

In [3]:
df = pd.read_csv("housing_dataset_week7.csv")
df.head()

,House_ID,Location,House_Type,Bedrooms,Bathrooms,Area_sqft,Age_Years,Parking,Price
0,1001,Kathmandu,Apartment,6,3,1603,8,Yes,11878334
1,1002,Kathmandu,Villa,4,1,722,3,Yes,20613608
2,1003,Kathmandu,Villa,2,4,1502,15,No,5436124
3,1004,Pokhara,Villa,4,3,1738,5,Yes,27588477
4,1005,Kathmandu,Apartment,4,1,2070,12,No,7915909

### Dataset Info

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   House_ID    50 non-null     int64
 1   Location    50 non-null     object
 2   House_Type  50 non-null     object
 3   Bedrooms    50 non-null     int64
 4   Bathrooms   50 non-null     int64
 5   Area_sqft   50 non-null     int64
 6   Age_Years   50 non-null     int64
 7   Parking     50 non-null     object
 8   Price       50 non-null     int64
dtypes: int64(6), object(3)
memory usage: 3.6+ KB

### Step 1: Create Price per Sqft

In [5]:
df["Price_per_sqft"] = df["Price"] / df["Area_sqft"]
df.head()

,House_ID,Location,House_Type,Bedrooms,Bathrooms,Area_sqft,Age_Years,Parking,Price,Price_per_sqft
0,1001,Kathmandu,Apartment,6,3,1603,8,Yes,11878334,7410.064878
1,1002,Kathmandu,Villa,4,1,722,3,Yes,20613608,28550.703601
2,1003,Kathmandu,Villa,2,4,1502,15,No,5436124,3619.256991
3,1004,Pokhara,Villa,4,3,1738,5,Yes,27588477,15873.692175
4,1005,Kathmandu,Apartment,4,1,2070,12,No,7915909,3824.110628

### Step 2: Create Total Rooms

In [6]:
df["Total_Rooms"] = df["Bedrooms"] + df["Bathrooms"]
df.head()

,House_ID,Location,House_Type,Bedrooms,Bathrooms,Area_sqft,Age_Years,Parking,Price,Price_per_sqft,Total_Rooms
0,1001,Kathmandu,Apartment,6,3,1603,8,Yes,11878334,7410.064878,9
1,1002,Kathmandu,Villa,4,1,722,3,Yes,20613608,28550.703601,5
2,1003,Kathmandu,Villa,2,4,1502,15,No,5436124,3619.256991,6
3,1004,Pokhara,Villa,4,3,1738,5,Yes,27588477,15873.692175,7
4,1005,Kathmandu,Apartment,4,1,2070,12,No,7915909,3824.110628,5

### Step 3: Create House Age Category
###### 0–5 → New
###### 6–15 → Medium
###### 16+ → Old

In [7]:
def age_category(age):
    if age <= 5:
        return "New"
    elif age <= 15:
        return "Medium"
    else:
        return "Old"

df["House_Age_Category"] = df["Age_Years"].apply(age_category)
df.head()

,House_ID,Location,House_Type,Bedrooms,Bathrooms,Area_sqft,Age_Years,Parking,Price,Price_per_sqft,Total_Rooms,House_Age_Category
0,1001,Kathmandu,Apartment,6,3,1603,8,Yes,11878334,7410.064878,9,Medium
1,1002,Kathmandu,Villa,4,1,722,3,Yes,20613608,28550.703601,5,New
2,1003,Kathmandu,Villa,2,4,1502,15,No,5436124,3619.256991,6,Medium
3,1004,Pokhara,Villa,4,3,1738,5,Yes,27588477,15873.692175,7,New
4,1005,Kathmandu,Apartment,4,1,2070,12,No,7915909,3824.110628,5,Medium

### Step 4: Create Luxury House Feature

###### If Price > 30,000,000 → Luxury

In [8]:
df["Luxury_House"] = np.where(df["Price"] > 30000000, 1, 0)
df.head()

,House_ID,Location,House_Type,Bedrooms,Bathrooms,Area_sqft,Age_Years,Parking,Price,Price_per_sqft,Total_Rooms,House_Age_Category,Luxury_House
0,1001,Kathmandu,Apartment,6,3,1603,8,Yes,11878334,7410.064878,9,Medium,0
1,1002,Kathmandu,Villa,4,1,722,3,Yes,20613608,28550.703601,5,New,0
2,1003,Kathmandu,Villa,2,4,1502,15,No,5436124,3619.256991,6,Medium,0
3,1004,Pokhara,Villa,4,3,1738,5,Yes,27588477,15873.692175,7,New,0
4,1005,Kathmandu,Apartment,4,1,2070,12,No,7915909,3824.110628,5,Medium,0

### Step 5: Create Big House Feature

In [9]:
df["Big_House"] = np.where(df["Area_sqft"] > 2000, 1, 0)
df.head()

,House_ID,Location,House_Type,Bedrooms,Bathrooms,Area_sqft,Age_Years,Parking,Price,Price_per_sqft,Total_Rooms,House_Age_Category,Luxury_House,Big_House
0,1001,Kathmandu,Apartment,6,3,1603,8,Yes,11878334,7410.064878,9,Medium,0,0
1,1002,Kathmandu,Villa,4,1,722,3,Yes,20613608,28550.703601,5,New,0,0
2,1003,Kathmandu,Villa,2,4,1502,15,No,5436124,3619.256991,6,Medium,0,0
3,1004,Pokhara,Villa,4,3,1738,5,Yes,27588477,15873.692175,7,New,0,0
4,1005,Kathmandu,Apartment,4,1,2070,12,No,7915909,3824.110628,5,Medium,0,1

### Check New Columns

In [10]:
df.columns

Index(['House_ID', 'Location', 'House_Type', 'Bedrooms', 'Bathrooms',
       'Area_sqft', 'Age_Years', 'Parking', 'Price', 'Price_per_sqft',
       'Total_Rooms', 'House_Age_Category', 'Luxury_House', 'Big_House'],
      dtype='object')

### Final Dataset

In [11]:
df.head()

,House_ID,Location,House_Type,Bedrooms,Bathrooms,Area_sqft,Age_Years,Parking,Price,Price_per_sqft,Total_Rooms,House_Age_Category,Luxury_House,Big_House
0,1001,Kathmandu,Apartment,6,3,1603,8,Yes,11878334,7410.064878,9,Medium,0,0
1,1002,Kathmandu,Villa,4,1,722,3,Yes,20613608,28550.703601,5,New,0,0
2,1003,Kathmandu,Villa,2,4,1502,15,No,5436124,3619.256991,6,Medium,0,0
3,1004,Pokhara,Villa,4,3,1738,5,Yes,27588477,15873.692175,7,New,0,0
4,1005,Kathmandu,Apartment,4,1,2070,12,No,7915909,3824.110628,5,Medium,0,1

### Save Dataset

In [12]:
df.to_csv("housing_feature_engineered.csv", index=False)

## Conclusion

In this task, I learned feature engineering techniques by creating new features from existing housing dataset columns. I created numerical, categorical, and binary features such as Price_per_sqft, Total_Rooms, House_Age_Category, Luxury_House, and Big_House. Feature engineering improves data quality and enhances machine learning model performance.