# Week 6 Day 4: Fix Data Types

---
## Internship Details

**Intern Name:** Dinesh Singh Dhami  
**Semester:** BE Computer 8th Semester  
**Company:** Sipalaya Info Tech, Kathmandu-32, Koteshwor  
**Domain:** Data Science  
**Task:** Fix Data Types  
**Tools Used:** Python, Pandas, NumPy, Jupyter Notebook  

---

## Objective

The objective of this task is to identify incorrect data types in datasets and convert them into appropriate formats such as numeric, datetime, and categorical types for better analysis and preprocessing.

### Import Libraries

In [1]:
import pandas as pd
import numpy as np

### Load Datasets

In [3]:
df = pd.read_csv("wrong_datatypes_dataset.csv")
df

   Employee_ID  Name          Age  Salary      Join_Date Department
0         1001   Ram           22   50000     2024-01-15         IT
1         1002  Hari           24   45000     15/03/2024         HR
2         1003  Sita  twenty five   55000  March 22 2024    Finance
3         1004  Gita           23   48000     2024/05/10         IT
4         1005  Rita           26  52,000   invalid_date      Sales

### Check Dataset Info

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Age          5 non-null      object
 3   Salary       5 non-null      object
 4   Join_Date    5 non-null      object
 5   Department   5 non-null      object
dtypes: int64(1), object(5)
memory usage: 368.0+ bytes

### Fix Age Column

In [6]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [7]:
df

   Employee_ID  Name   Age  Salary      Join_Date Department
0         1001   Ram  22.0   50000     2024-01-15         IT
1         1002  Hari  24.0   45000     15/03/2024         HR
2         1003  Sita   NaN   55000  March 22 2024    Finance
3         1004  Gita  23.0   48000     2024/05/10         IT
4         1005  Rita  26.0  52,000   invalid_date      Sales

### Fix Salary Column

###### First remove commas:

In [8]:
df["Salary"] = df["Salary"].str.replace(",", "")

###### Convert to numeric:

In [9]:
df["Salary"] = pd.to_numeric(df["Salary"])

###### Check

In [10]:
df

   Employee_ID  Name   Age  Salary      Join_Date Department
0         1001   Ram  22.0   50000     2024-01-15         IT
1         1002  Hari  24.0   45000     15/03/2024         HR
2         1003  Sita   NaN   55000  March 22 2024    Finance
3         1004  Gita  23.0   48000     2024/05/10         IT
4         1005  Rita  26.0   52000   invalid_date      Sales

### Fix Join_Date Column

In [14]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
# Valid dates converted
# invalid_date becomes NaT

In [15]:
df

   Employee_ID  Name   Age  Salary  Join_Date Department
0         1001   Ram  22.0   50000 2024-01-15         IT
1         1002  Hari  24.0   45000        NaT         HR
2         1003  Sita   NaN   55000        NaT    Finance
3         1004  Gita  23.0   48000        NaT         IT
4         1005  Rita  26.0   52000        NaT      Sales

### Final Check

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Age          4 non-null      float64
 3   Salary       5 non-null      int64
 4   Join_Date    1 non-null      datetime64[ns]
 5   Department   5 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 368.0+ bytes

### Save Clean Dataset

In [18]:
df.to_csv("fixed_datatypes_dataset.csv", index=False)

## Conclusion

In this task, I learned how to identify and fix incorrect data types in datasets using Pandas. I converted object-type columns into numeric and datetime formats using to_numeric() and to_datetime(). Fixing data types improves data quality and ensures better preprocessing for analysis and machine learning.