# Week 5 Day 1: Missing Value Handling using Pandas

**Intern Name:** Dinesh Singh Dhami  
**Semester:** BE Computer 8th Semester  
**Company:** Sipalaya Info Tech, Kathmandu-32, Koteshwor  
**Domain:** Data Science  
**Task:** Missing Value Handling using Pandas  
**Tools Used:** Python, Pandas, Jupyter Notebook

## Objective
The objective of this task is to learn how to identify and handle missing values in datasets using Pandas. Missing value handling is one of the most important steps in data cleaning and preprocessing.

### Import Libraries

In [17]:
import pandas as pd
import numpy as np

### Create Dataset with Missing Values

In [18]:
data = {
    "Name": ["Ram", "Hari", "Sita", "Gita", "Rita"],
    "Age": [22, None, 24, 23, None],
    "Salary": [50000, 45000, None, 55000, 52000]
}

df = pd.DataFrame(data)
df

   Name   Age   Salary
0   Ram  22.0  50000.0
1  Hari   NaN  45000.0
2  Sita  24.0      NaN
3  Gita  23.0  55000.0
4  Rita   NaN  52000.0

#### Task 1: Find Null Values

###### Check Null Values

In [19]:
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False
4  False   True   False

###### Count Null Values

In [20]:
df.isnull().sum()

Name      0
Age       2
Salary    1
dtype: int64

###### Dataset Info

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     3 non-null      float64
 2   Salary  4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 248.0+ bytes

### Task 2: Remove Null Rows and Columns

###### Remove Rows with Null Values

In [22]:
df.dropna()

   Name   Age   Salary
0   Ram  22.0  50000.0
3  Gita  23.0  55000.0

###### Remove Columns with Null Values

In [23]:
df.dropna(axis=1)

   Name
0   Ram
1  Hari
2  Sita
3  Gita
4  Rita

### Task 3: Fill Missing Values

###### Fill Using Mean

In [24]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

   Name   Age   Salary
0   Ram  22.0  50000.0
1  Hari  23.0  45000.0
2  Sita  24.0      NaN
3  Gita  23.0  55000.0
4  Rita  23.0  52000.0

###### Fill Using Median

In [25]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
df

   Name   Age   Salary
0   Ram  22.0  50000.0
1  Hari  23.0  45000.0
2  Sita  24.0  51000.0
3  Gita  23.0  55000.0
4  Rita  23.0  52000.0

###### Fill Using Mode

In [26]:
df["Age"] = df["Age"].fillna(df["Age"].mode()[0])
df

   Name   Age   Salary
0   Ram  22.0  50000.0
1  Hari  23.0  45000.0
2  Sita  24.0  51000.0
3  Gita  23.0  55000.0
4  Rita  23.0  52000.0

### Real Dataset Practice

In [29]:
import pandas as pd

df = pd.read_csv("customer_data.csv")
df.head()

   Customer_ID  Name   Age  Gender       City   Salary  Purchase_Amount
0          101   Ram  22.0    Male  Kathmandu  50000.0           1200.0
1          102  Hari   NaN    Male    Pokhara  45000.0           1500.0
2          103  Sita  24.0  Female        NaN  52000.0           1800.0
3          104  Gita  23.0  Female   Lalitpur      NaN           2000.0
4          105  Rita   NaN  Female  Bhaktapur  55000.0              NaN

###### Check missing values:

In [30]:
df.isnull().sum()

Customer_ID        0
Name               0
Age                2
Gender             0
City               1
Salary             1
Purchase_Amount    1
dtype: int64

In [31]:
df.dropna()

   Customer_ID    Name   Age  Gender       City   Salary  Purchase_Amount
0          101     Ram  22.0    Male  Kathmandu  50000.0           1200.0
5          106  Aayush  26.0    Male  Kathmandu  60000.0           2500.0
6          107   Nisha  25.0  Female    Pokhara  48000.0           1700.0

In [32]:
df.fillna(df.mean(numeric_only=True))

   Customer_ID    Name   Age  Gender       City        Salary  Purchase_Amount
0          101     Ram  22.0    Male  Kathmandu  50000.000000      1200.000000
1          102    Hari  24.0    Male    Pokhara  45000.000000      1500.000000
2          103    Sita  24.0  Female        NaN  52000.000000      1800.000000
3          104    Gita  23.0  Female   Lalitpur  51666.666667      2000.000000
4          105    Rita  24.0  Female  Bhaktapur  55000.000000      1783.333333
5          106  Aayush  26.0    Male  Kathmandu  60000.000000      2500.000000
6          107   Nisha  25.0  Female    Pokhara  48000.000000      1700.000000

## Conclusion
In this task, I learned how to identify and handle missing values using Pandas. I practiced detecting null values using isnull(), removing null rows and columns using dropna(), and filling missing values using mean, median, and mode. These techniques are essential for data cleaning and preprocessing.