# Week 6 Day 6 Assignment: Clean Employee Salary Dataset

---
## Internship Details

**Intern Name:** Dinesh Singh Dhami  
**Semester:** BE Computer 8th Semester  
**Company:** Sipalaya Info Tech, Kathmandu-32, Koteshwor  
**Domain:** Data Science  
**Assignment:** Clean Employee Salary Dataset  
**Tools Used:** Python, Pandas, NumPy, Jupyter Notebook  

---

## Objective

The objective of this assignment is to clean a real-world employee salary dataset by handling missing values, duplicate records, outliers, incorrect data types, and inconsistent string formatting. The final cleaned dataset will be ready for analysis and machine learning tasks.

### Import Libraries

In [25]:
import pandas as pd
import numpy as np

### Load Datasets

In [26]:
df = pd.read_csv("employee_salary_dirty_dataset.csv")
df

,Employee_ID,Employee_Name,Department,Salary,Experience_Years,Joining_Date,Gender,City,Employment_Type
0,1001,ram shrestha,IT,45000,2.0,2024-01-15,Male,Kathmandu,Full Time
1,1002,SITA THAPA,hr,48000,3.0,15/02/2024,female,pokhara,Full Time
2,1003,Hari KC,Finance,NaN,5.0,2024/03/20,MALE,Lalitpur,Part Time
3,1004,gita rai,IT,52000,NaN,March 25 2024,Female,Bhaktapur,Full Time
4,1005,Nisha Tamang,sales,55000,4.0,invalid_date,F,Kathmandu,Contract
5,1006,Aayush Lama,Marketing,60000,6.0,2024-05-12,M,Pokhara,Full Time
6,1007,Rita Karki,HR,"52,000",3.0,2024-06-18,female,Lalitpur,Part Time
7,1008,Bikash Gurung,Finance,250000,8.0,2024-07-10,Male,Bhaktapur,Full Time
8,1009,Sunita Bista,IT,30000,1.0,2024-08-05,Female,Kathmandu,Contract
9,1010,Mina Basnet,Sales,58000,4.0,2024-09-11,FEMALE,pokhara,Full Time
10,1001,ram shrestha,IT,45000,2.0,2024-01-15,Male,Kathmandu,Full Time
11,1004,gita rai,IT,52000,NaN,March 25 2024,Female,Bhaktapur,Full Time

### Dataset Information

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       12 non-null     int64
 1   Employee_Name     12 non-null     object
 2   Department        12 non-null     object
 3   Salary            11 non-null     object
 4   Experience_Years  10 non-null     float64
 5   Joining_Date      12 non-null     object
 6   Gender            12 non-null     object
 7   City              12 non-null     object
 8   Employment_Type   12 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 992.0+ bytes

In [28]:
df.shape

(12, 9)

### Check Missing Values

##### Fill Salary

###### First remove commas:

In [29]:
df["Salary"] = df["Salary"].astype(str).str.replace(",", "")

###### Convert numeric:

In [30]:
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

###### Fill missing salary:

In [31]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

### Fill Experience

In [32]:
df["Experience_Years"] = pd.to_numeric(df["Experience_Years"], errors="coerce")
df["Experience_Years"] = df["Experience_Years"].fillna(df["Experience_Years"].mean())

### Check Duplicates

In [33]:
df.duplicated().sum()

2

### Remove Duplicates

In [34]:
df = df.drop_duplicates()

### Fix Data Types

In [37]:
df = df.copy()
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"], errors="coerce")

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       10 non-null     int64
 1   Employee_Name     10 non-null     object
 2   Department        10 non-null     object
 3   Salary            10 non-null     float64
 4   Experience_Years  10 non-null     float64
 5   Joining_Date      6 non-null      datetime64[ns]
 6   Gender            10 non-null     object
 7   City              10 non-null     object
 8   Employment_Type   10 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 800.0+ bytes

### Detect Outliers using IQR

In [39]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(lower, upper)

36625.0 69625.0

### Find Outliers

In [40]:
outliers = df[(df["Salary"] < lower) | (df["Salary"] > upper)]
outliers

,Employee_ID,Employee_Name,Department,Salary,Experience_Years,Joining_Date,Gender,City,Employment_Type
7,1008,Bikash Gurung,Finance,250000.0,8.0,2024-07-10,Male,Bhaktapur,Full Time
8,1009,Sunita Bista,IT,30000.0,1.0,2024-08-05,Female,Kathmandu,Contract

### Handle Outliers using Capping

In [41]:
df["Salary"] = np.where(df["Salary"] > upper, upper, df["Salary"])
df["Salary"] = np.where(df["Salary"] < lower, lower, df["Salary"])

### String Cleaning

##### Employee Name:

In [42]:
df["Employee_Name"] = df["Employee_Name"].str.strip().str.title()

##### Department:

In [43]:
df["Department"] = df["Department"].str.strip().str.title()

##### City:

In [44]:
df["City"] = df["City"].str.strip().str.title()

#### Gender cleaning:

In [45]:
df["Gender"] = df["Gender"].str.strip().str.title()

df["Gender"] = df["Gender"].replace({
    "M": "Male",
    "F": "Female"
})

##### Employment Type:

In [46]:
df["Employment_Type"] = df["Employment_Type"].str.strip().str.title()

### Final Check

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       10 non-null     int64
 1   Employee_Name     10 non-null     object
 2   Department        10 non-null     object
 3   Salary            10 non-null     float64
 4   Experience_Years  10 non-null     float64
 5   Joining_Date      6 non-null      datetime64[ns]
 6   Gender            10 non-null     object
 7   City              10 non-null     object
 8   Employment_Type   10 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 800.0+ bytes

###### or

In [48]:
df

,Employee_ID,Employee_Name,Department,Salary,Experience_Years,Joining_Date,Gender,City,Employment_Type
0,1001,Ram Shrestha,It,45000.0,2.0,2024-01-15,Male,Kathmandu,Full Time
1,1002,Sita Thapa,Hr,48000.0,3.0,NaT,Female,Pokhara,Full Time
2,1003,Hari Kc,Finance,52000.0,5.0,NaT,Male,Lalitpur,Part Time
3,1004,Gita Rai,It,52000.0,3.8,NaT,Female,Bhaktapur,Full Time
4,1005,Nisha Tamang,Sales,55000.0,4.0,NaT,Female,Kathmandu,Contract
5,1006,Aayush Lama,Marketing,60000.0,6.0,2024-05-12,Male,Pokhara,Full Time
6,1007,Rita Karki,Hr,52000.0,3.0,2024-06-18,Female,Lalitpur,Part Time
7,1008,Bikash Gurung,Finance,69625.0,8.0,2024-07-10,Male,Bhaktapur,Full Time
8,1009,Sunita Bista,It,36625.0,1.0,2024-08-05,Female,Kathmandu,Contract
9,1010,Mina Basnet,Sales,58000.0,4.0,2024-09-11,Female,Pokhara,Full Time

### Save Clean Dataset

In [49]:
df.to_csv("employee_salary_cleaned_dataset.csv", index=False)

## Insights

- Missing values successfully handled.
- Duplicate rows removed.
- Outliers detected and capped using IQR.
- Incorrect data types fixed.
- String formatting standardized.
- Final dataset is clean and ready for analysis.

## Conclusion

In this assignment, I performed complete data cleaning on an employee salary dataset using Pandas and NumPy. I handled missing values, removed duplicate records, fixed incorrect data types, detected and handled outliers using IQR, and cleaned inconsistent string values. This assignment improved my practical understanding of real-world data preprocessing workflows.