# Week 5 Day 2: Forward Fill and Backward Fill using Pandas

**Intern Name:** Dinesh Singh Dhami  
**Semester:** BE Computer 8th Semester  
**Company:** Sipalaya Info Tech, Kathmandu-32, Koteshwor  
**Domain:** Data Science  
**Task:** Forward Fill and Backward Fill  
**Tools Used:** Python, Pandas, Jupyter Notebook

## Objective
The objective of this task is to learn how to handle missing values using forward fill and backward fill methods in Pandas. These techniques are useful when working with sequential or time-series data.

### Import Libraries

In [2]:
import pandas as pd
import numpy as np

### Create Sample Dataset

In [3]:
data = {
    "Day": [1, 2, 3, 4, 5, 6],
    "Sales": [1000, None, None, 1500, None, 2000]
}

df = pd.DataFrame(data)
df

   Day   Sales
0    1  1000.0
1    2     NaN
2    3     NaN
3    4  1500.0
4    5     NaN
5    6  2000.0

#### Task 1: Forward Fill

In [6]:
df.ffill()
###### Row 2 takes value from Row 1
###### Row 3 also takes previous filled value
###### Row 5 takes value from Row 4

   Day   Sales
0    1  1000.0
1    2  1000.0
2    3  1000.0
3    4  1500.0
4    5  1500.0
5    6  2000.0

#### Task 2: Backward Fill

In [7]:
df.bfill()

   Day   Sales
0    1  1000.0
1    2  1500.0
2    3  1500.0
3    4  1500.0
4    5  2000.0
5    6  2000.0

#### Task 3: Apply on Real Dataset

In [8]:
df = pd.read_csv("customer_data.csv")
df

   Customer_ID    Name   Age  Gender       City   Salary  Purchase_Amount
0          101     Ram  22.0    Male  Kathmandu  50000.0           1200.0
1          102    Hari   NaN    Male    Pokhara  45000.0           1500.0
2          103    Sita  24.0  Female        NaN  52000.0           1800.0
3          104    Gita  23.0  Female   Lalitpur      NaN           2000.0
4          105    Rita   NaN  Female  Bhaktapur  55000.0              NaN
5          106  Aayush  26.0    Male  Kathmandu  60000.0           2500.0
6          107   Nisha  25.0  Female    Pokhara  48000.0           1700.0

###### Check missing values:

In [9]:
df.isnull().sum()

Customer_ID        0
Name               0
Age                2
Gender             0
City               1
Salary             1
Purchase_Amount    1
dtype: int64

###### Apply Forward Fill

In [10]:
df.ffill()

   Customer_ID    Name   Age  Gender       City   Salary  Purchase_Amount
0          101     Ram  22.0    Male  Kathmandu  50000.0           1200.0
1          102    Hari  22.0    Male    Pokhara  45000.0           1500.0
2          103    Sita  24.0  Female    Pokhara  52000.0           1800.0
3          104    Gita  23.0  Female   Lalitpur  52000.0           2000.0
4          105    Rita  23.0  Female  Bhaktapur  55000.0           2000.0
5          106  Aayush  26.0    Male  Kathmandu  60000.0           2500.0
6          107   Nisha  25.0  Female    Pokhara  48000.0           1700.0

###### Apply Backward Fill

In [11]:
df.bfill()

   Customer_ID    Name   Age  Gender       City   Salary  Purchase_Amount
0          101     Ram  22.0    Male  Kathmandu  50000.0           1200.0
1          102    Hari  24.0    Male    Pokhara  45000.0           1500.0
2          103    Sita  24.0  Female   Lalitpur  52000.0           1800.0
3          104    Gita  23.0  Female   Lalitpur  55000.0           2000.0
4          105    Rita  26.0  Female  Bhaktapur  55000.0           2500.0
5          106  Aayush  26.0    Male  Kathmandu  60000.0           2500.0
6          107   Nisha  25.0  Female    Pokhara  48000.0           1700.0

### When to Use?
##### Use Forward Fill:
Time-series data, Stock prices, Daily sales records
##### Use Backward Fill:
When next value is more relevant

## Conclusion
In this task, I learned how to handle missing values using forward fill and backward fill methods in Pandas. Forward fill replaces missing values using previous valid values, while backward fill uses next valid values. These techniques are useful for sequential and time-series datasets.