## Merge Datasets in Pandas.
##### This is a very important real-world topic because in companies data usually comes from multiple files/tables.

### Import Pandas

In [1]:
import pandas as pd

### Create Dataset 1

In [2]:
student_info = {
    "Student_ID": [1, 2, 3],
    "Name": ["Ram", "Hari", "Sita"],
    "Age": [20, 21, 19]
}

df1 = pd.DataFrame(student_info)

print("Student Info Dataset:")
print(df1)

Student Info Dataset:
   Student_ID  Name  Age
0           1   Ram   20
1           2  Hari   21
2           3  Sita   19

### Create Dataset 2

In [3]:
marks_data = {
    "Student_ID": [1, 2, 3],
    "Marks": [80, 75, 90]
}

df2 = pd.DataFrame(marks_data)

print("Marks Dataset:")
print(df2)

Marks Dataset:
   Student_ID  Marks
0           1     80
1           2     75
2           3     90

### Merge Datasets

In [4]:
merged_df = pd.merge(df1, df2, on="Student_ID")
print(merged_df)

   Student_ID  Name  Age  Marks
0           1   Ram   20     80
1           2  Hari   21     75
2           3  Sita   19     90

### Types of Merge
##### There are 4 important types:
##### 1. Inner Join
##### 2. Left Join
##### 3. Right Join
##### 4. Outer Join

### #Inner Merge (Common Rows Only)

In [5]:
pd.merge(df1, df2, on="Student_ID", how="inner")

   Student_ID  Name  Age  Marks
0           1   Ram   20     80
1           2  Hari   21     75
2           3  Sita   19     90

### #Left Merge

In [6]:
pd.merge(df1, df2, on="Student_ID", how="left")

   Student_ID  Name  Age  Marks
0           1   Ram   20     80
1           2  Hari   21     75
2           3  Sita   19     90

### #Right Merge

In [7]:
pd.merge(df1, df2, on="Student_ID", how="right")

   Student_ID  Name  Age  Marks
0           1   Ram   20     80
1           2  Hari   21     75
2           3  Sita   19     90

### #Outer Merge

In [8]:
pd.merge(df1, df2, on="Student_ID", how="outer")

   Student_ID  Name  Age  Marks
0           1   Ram   20     80
1           2  Hari   21     75
2           3  Sita   19     90

## Full Practice Code

In [10]:
import pandas as pd

student_info = {
    "Student_ID": [1, 2, 3],
    "Name": ["Ram", "Hari", "Sita"],
    "Age": [20, 21, 19]
}

marks_data = {
    "Student_ID": [1, 2, 3],
    "Marks": [80, 75, 90]
}

df1 = pd.DataFrame(student_info)
df2 = pd.DataFrame(marks_data)

print("Student Info:")
print(df1)

print("\nMarks Data:")
print(df2)

merged_df = pd.merge(df1, df2, on="Student_ID")

print("\nMerged Dataset:")
print(merged_df)

Student Info:
   Student_ID  Name  Age
0           1   Ram   20
1           2  Hari   21
2           3  Sita   19

Marks Data:
   Student_ID  Marks
0           1     80
1           2     75
2           3     90

Merged Dataset:
   Student_ID  Name  Age  Marks
0           1   Ram   20     80
1           2  Hari   21     75
2           3  Sita   19     90