### Import Pandas

In [14]:
import pandas as pd

### Create Data

In [15]:
data = {
    "Name": ["Ram", "Hari", "Sita"],
    "Age": [20, 21, 19],
    "Marks": [80, 75, 90]
}

### Convert into DataFrame

In [16]:
df = pd.DataFrame(data)

### Print DataFrame

In [17]:
print(df)

   Name  Age  Marks
0   Ram   20     80
1  Hari   21     75
2  Sita   19     90

### Read CSV File

In [18]:
df = pd.read_csv("students.csv")

In [21]:
df = pd.read_csv("students.csv")
print(df)

   Name  Age  Marks
0   Ram   20     80
1  Hari   21     75
2  Sita   19     90

In [22]:
# Shows first 5 rows.
df.head()

   Name  Age  Marks
0   Ram   20     80
1  Hari   21     75
2  Sita   19     90

In [23]:
# Shows last 5 rows.
df.tail()

   Name  Age  Marks
0   Ram   20     80
1  Hari   21     75
2  Sita   19     90

In [24]:
# Shows dataset info.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes

In [26]:
# Shows statistics.
df.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  81.666667
std     1.0   7.637626
min    19.0  75.000000
25%    19.5  77.500000
50%    20.0  80.000000
75%    20.5  85.000000
max    21.0  90.000000

## Final Full Code

In [27]:
import pandas as pd

data = {
    "Name": ["Ram", "Hari", "Sita"],
    "Age": [20, 21, 19],
    "Marks": [80, 75, 90]
}

df = pd.DataFrame(data)

print("DataFrame:")
print(df)

print("\nFirst 5 rows:")
print(df.head())

print("\nLast 5 rows:")
print(df.tail())

print("\nInfo:")
print(df.info())

print("\nStatistics:")
print(df.describe())

DataFrame:
   Name  Age  Marks
0   Ram   20     80
1  Hari   21     75
2  Sita   19     90

First 5 rows:
   Name  Age  Marks
0   Ram   20     80
1  Hari   21     75
2  Sita   19     90

Last 5 rows:
   Name  Age  Marks
0   Ram   20     80
1  Hari   21     75
2  Sita   19     90

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes
None

Statistics:
        Age      Marks
count   3.0   3.000000
mean   20.0  81.666667
std     1.0   7.637626
min    19.0  75.000000
25%    19.5  77.500000
50%    20.0  80.000000
75%    20.5  85.000000
max    21.0  90.000000