# Week 6 Day 1: Remove Duplicates using Pandas

---
### Internship Details

**Intern Name:** Dinesh Singh Dhami  
**Semester:** BE Computer 8th Semester  
**Company:** Sipalaya Info Tech, Kathmandu-32, Koteshwor  
**Domain:** Data Science  
**Task:** Remove Duplicate Records  
**Tools Used:** Python, Pandas, Jupyter Notebook  

---

## Objective

The objective of this task is to identify and remove duplicate records from datasets using Pandas. Duplicate records can negatively affect data quality, analytics, and machine learning performance.

### Import Libraries

In [1]:
import pandas as pd
import numpy as np

#### Load Dataset

In [3]:
df = pd.read_csv("duplicates_practice_dataset.csv")
df.head()

   Customer_ID  Name  Age       City  Salary Department
0          101   Ram   22  Kathmandu   50000         IT
1          102  Hari   24    Pokhara   45000         HR
2          103  Sita   25   Lalitpur   55000    Finance
3          104  Gita   23  Bhaktapur   48000         IT
4          105  Rita   26  Kathmandu   52000         HR

#### Dataset Shape

In [5]:
df.shape

(10, 6)

### Detect Duplicate Records

In [7]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8    False
9    False
dtype: bool

### Count Duplicates

In [8]:
df.duplicated().sum()

3

### View Duplicate Rows

In [10]:
duplicates = df[df.duplicated()]
duplicates

   Customer_ID  Name  Age       City  Salary Department
5          101   Ram   22  Kathmandu   50000         IT
6          103  Sita   25   Lalitpur   55000    Finance
7          104  Gita   23  Bhaktapur   48000         IT

### Remove Duplicates

In [11]:
df_cleaned = df.drop_duplicates()
df_cleaned

   Customer_ID    Name  Age       City  Salary Department
0          101     Ram   22  Kathmandu   50000         IT
1          102    Hari   24    Pokhara   45000         HR
2          103    Sita   25   Lalitpur   55000    Finance
3          104    Gita   23  Bhaktapur   48000         IT
4          105    Rita   26  Kathmandu   52000         HR
8          106  Aayush   27    Pokhara   62000      Sales
9          107   Nisha   24  Kathmandu   47000  Marketing

### Compare Shape

In [12]:
print("Before:", df.shape)
print("After:", df_cleaned.shape)

Before: (10, 6)
After: (7, 6)

### Verify Final Dataset

In [13]:
df_cleaned.duplicated().sum()

0

## Conclusion

In this task, I learned how to detect and remove duplicate records using Pandas. I used duplicated() to identify duplicate rows and drop_duplicates() to remove them. Removing duplicates improves data quality and ensures accurate analysis.