# Week 5 Day 3: Customer Dataset Cleaning Assignment

**Intern Name:** Dinesh Singh Dhami**  
**Semester:** BE Computer 8th Semester  
**Company:** Sipalaya Info Tech, Kathmandu-32, Koteshwor  
**Domain:** Data Science  
**Assignment:** Customer Dataset Cleaning  
**Tools Used:** Python, Pandas, NumPy, Jupyter Notebook

## Objective
The objective of this assignment is to clean a customer dataset by identifying missing values, handling null records, filling missing values using suitable techniques, and preparing the dataset for further analysis.

### Import Libraries

In [2]:
import pandas as pd
import numpy as np

### Load Dataset

In [3]:
df = pd.read_csv("customer_data.csv")
df

,Customer_ID,Name,Age,Gender,City,Salary,Purchase_Amount,Membership_Type,Join_Date,Last_Purchase_Date,Email,Phone,Satisfaction_Score,Payment_Method
0,1001,Customer_1,NaN,Male,Kathmandu,NaN,1800.0,Gold,2024-04-05,2025-12-04,customer1@gmail.com,9883197857,3.0,Bank Transfer
1,1002,Customer_2,22.0,Male,Kathmandu,50000.0,1500.0,Bronze,2024-10-01,2025-09-07,customer2@gmail.com,9897226012,NaN,Card
2,1003,Customer_3,28.0,female,Lalitpur,200000.0,1200.0,Gold,2024-12-14,2025-06-09,customer3@gmail.com,9830868105,4.0,eSewa
3,1004,Customer_4,22.0,Male,Bhaktapur,45000.0,1800.0,Silver,2024-10-09,2025-01-24,customer4@gmail.com,9871662963,3.0,Bank Transfer
4,1005,Customer_5,22.0,female,Lalitpur,200000.0,NaN,Bronze,2024-06-19,2025-04-23,customer5@gmail.com,9819335534,3.0,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,1098,Customer_98,22.0,FEMALE,Bhaktapur,55000.0,1200.0,Bronze,2024-11-25,2025-12-02,customer98@gmail.com,9891390501,NaN,eSewa
98,1099,Customer_99,24.0,female,Lalitpur,50000.0,NaN,Gold,2024-10-09,2025-11-25,customer99@gmail.com,9898473848,4.0,Cash
99,1100,Customer_100,NaN,FEMALE,Kathmandu,55000.0,2200.0,Gold,2024-10-12,2025-12-05,customer100@gmail.com,9822097496,5.0,eSewa
100,1006,Customer_6,26.0,Male,Pokhara,200000.0,1200.0,Silver,2024-05-15,2025-11-27,customer6@gmail.com,9858966946,4.0,eSewa
101,1011,Customer_11,24.0,male,NaN,60000.0,1200.0,Gold,2024-02-05,2025-11-06,customer11@gmail.com,9866661351,3.0,Bank Transfer

### Check Dataset Information

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         102 non-null    int64
 1   Name                102 non-null    object
 2   Age                 87 non-null     float64
 3   Gender              102 non-null    object
 4   City                82 non-null     object
 5   Salary              92 non-null     float64
 6   Purchase_Amount     85 non-null     float64
 7   Membership_Type     102 non-null    object
 8   Join_Date           102 non-null    object
 9   Last_Purchase_Date  102 non-null    object
 10  Email               102 non-null    object
 11  Phone               102 non-null    int64
 12  Satisfaction_Score  77 non-null     float64
 13  Payment_Method      102 non-null    object
dtypes: float64(4), int64(2), object(8)
memory usage: 11.3+ KB

In [5]:
df.shape

(102, 14)

In [6]:
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Purchase_Amount,Membership_Type,Join_Date,Last_Purchase_Date,Email,Phone,Satisfaction_Score,Payment_Method
0,1001,Customer_1,NaN,Male,Kathmandu,NaN,1800.0,Gold,2024-04-05,2025-12-04,customer1@gmail.com,9883197857,3.0,Bank Transfer
1,1002,Customer_2,22.0,Male,Kathmandu,50000.0,1500.0,Bronze,2024-10-01,2025-09-07,customer2@gmail.com,9897226012,NaN,Card
2,1003,Customer_3,28.0,female,Lalitpur,200000.0,1200.0,Gold,2024-12-14,2025-06-09,customer3@gmail.com,9830868105,4.0,eSewa
3,1004,Customer_4,22.0,Male,Bhaktapur,45000.0,1800.0,Silver,2024-10-09,2025-01-24,customer4@gmail.com,9871662963,3.0,Bank Transfer
4,1005,Customer_5,22.0,female,Lalitpur,200000.0,NaN,Bronze,2024-06-19,2025-04-23,customer5@gmail.com,9819335534,3.0,Card

### Find Missing Values

In [8]:
df.isnull()

,Customer_ID,Name,Age,Gender,City,Salary,Purchase_Amount,Membership_Type,Join_Date,Last_Purchase_Date,Email,Phone,Satisfaction_Score,Payment_Method
0,False,False,True,False,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,False,False,False,False,False,False,False,False,False,False,False,False,True,False
98,False,False,False,False,False,False,True,False,False,False,False,False,False,False
99,False,False,True,False,False,False,False,False,False,False,False,False,False,False
100,False,False,False,False,False,False,False,False,False,False,False,False,False,False
101,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum()

Customer_ID            0
Name                   0
Age                   15
Gender                 0
City                  20
Salary                10
Purchase_Amount       17
Membership_Type        0
Join_Date              0
Last_Purchase_Date     0
Email                  0
Phone                  0
Satisfaction_Score    25
Payment_Method         0
dtype: int64

### Check Duplicate Records

In [10]:
df.duplicated().sum()

2

### Remove Duplicate Records

In [11]:
df = df.drop_duplicates()
df

,Customer_ID,Name,Age,Gender,City,Salary,Purchase_Amount,Membership_Type,Join_Date,Last_Purchase_Date,Email,Phone,Satisfaction_Score,Payment_Method
0,1001,Customer_1,NaN,Male,Kathmandu,NaN,1800.0,Gold,2024-04-05,2025-12-04,customer1@gmail.com,9883197857,3.0,Bank Transfer
1,1002,Customer_2,22.0,Male,Kathmandu,50000.0,1500.0,Bronze,2024-10-01,2025-09-07,customer2@gmail.com,9897226012,NaN,Card
2,1003,Customer_3,28.0,female,Lalitpur,200000.0,1200.0,Gold,2024-12-14,2025-06-09,customer3@gmail.com,9830868105,4.0,eSewa
3,1004,Customer_4,22.0,Male,Bhaktapur,45000.0,1800.0,Silver,2024-10-09,2025-01-24,customer4@gmail.com,9871662963,3.0,Bank Transfer
4,1005,Customer_5,22.0,female,Lalitpur,200000.0,NaN,Bronze,2024-06-19,2025-04-23,customer5@gmail.com,9819335534,3.0,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Customer_96,28.0,MALE,NaN,50000.0,1200.0,Silver,2024-06-19,2025-05-21,customer96@gmail.com,9866949781,5.0,Bank Transfer
96,1097,Customer_97,26.0,male,Bhaktapur,200000.0,2200.0,Gold,2024-04-13,2025-10-12,customer97@gmail.com,9887149951,5.0,eSewa
97,1098,Customer_98,22.0,FEMALE,Bhaktapur,55000.0,1200.0,Bronze,2024-11-25,2025-12-02,customer98@gmail.com,9891390501,NaN,eSewa
98,1099,Customer_99,24.0,female,Lalitpur,50000.0,NaN,Gold,2024-10-09,2025-11-25,customer99@gmail.com,9898473848,4.0,Cash
99,1100,Customer_100,NaN,FEMALE,Kathmandu,55000.0,2200.0,Gold,2024-10-12,2025-12-05,customer100@gmail.com,9822097496,5.0,eSewa

### Fill Missing Age with Mean

In [14]:
df.loc[:, "Age"] = df["Age"].fillna(df["Age"].mean())
df

,Customer_ID,Name,Age,Gender,City,Salary,Purchase_Amount,Membership_Type,Join_Date,Last_Purchase_Date,Email,Phone,Satisfaction_Score,Payment_Method
0,1001,Customer_1,25.835294,Male,Kathmandu,NaN,1800.0,Gold,2024-04-05,2025-12-04,customer1@gmail.com,9883197857,3.0,Bank Transfer
1,1002,Customer_2,22.000000,Male,Kathmandu,50000.0,1500.0,Bronze,2024-10-01,2025-09-07,customer2@gmail.com,9897226012,NaN,Card
2,1003,Customer_3,28.000000,female,Lalitpur,200000.0,1200.0,Gold,2024-12-14,2025-06-09,customer3@gmail.com,9830868105,4.0,eSewa
3,1004,Customer_4,22.000000,Male,Bhaktapur,45000.0,1800.0,Silver,2024-10-09,2025-01-24,customer4@gmail.com,9871662963,3.0,Bank Transfer
4,1005,Customer_5,22.000000,female,Lalitpur,200000.0,NaN,Bronze,2024-06-19,2025-04-23,customer5@gmail.com,9819335534,3.0,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Customer_96,28.000000,MALE,NaN,50000.0,1200.0,Silver,2024-06-19,2025-05-21,customer96@gmail.com,9866949781,5.0,Bank Transfer
96,1097,Customer_97,26.000000,male,Bhaktapur,200000.0,2200.0,Gold,2024-04-13,2025-10-12,customer97@gmail.com,9887149951,5.0,eSewa
97,1098,Customer_98,22.000000,FEMALE,Bhaktapur,55000.0,1200.0,Bronze,2024-11-25,2025-12-02,customer98@gmail.com,9891390501,NaN,eSewa
98,1099,Customer_99,24.000000,female,Lalitpur,50000.0,NaN,Gold,2024-10-09,2025-11-25,customer99@gmail.com,9898473848,4.0,Cash
99,1100,Customer_100,25.835294,FEMALE,Kathmandu,55000.0,2200.0,Gold,2024-10-12,2025-12-05,customer100@gmail.com,9822097496,5.0,eSewa

### Fill Missing Salary with Median

In [17]:
df.loc[:, "Salary"] = df["Salary"].fillna(df["Salary"].median())
df

,Customer_ID,Name,Age,Gender,City,Salary,Purchase_Amount,Membership_Type,Join_Date,Last_Purchase_Date,Email,Phone,Satisfaction_Score,Payment_Method
0,1001.0,Customer_1,25.835294,Male,Kathmandu,55000.0,1800.0,Gold,2024-04-05,2025-12-04,customer1@gmail.com,9.883198e+09,3.0,Bank Transfer
1,1002.0,Customer_2,22.000000,Male,Kathmandu,50000.0,1500.0,Bronze,2024-10-01,2025-09-07,customer2@gmail.com,9.897226e+09,NaN,Card
2,1003.0,Customer_3,28.000000,female,Lalitpur,200000.0,1200.0,Gold,2024-12-14,2025-06-09,customer3@gmail.com,9.830868e+09,4.0,eSewa
3,1004.0,Customer_4,22.000000,Male,Bhaktapur,45000.0,1800.0,Silver,2024-10-09,2025-01-24,customer4@gmail.com,9.871663e+09,3.0,Bank Transfer
4,1005.0,Customer_5,22.000000,female,Lalitpur,200000.0,NaN,Bronze,2024-06-19,2025-04-23,customer5@gmail.com,9.819336e+09,3.0,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,1097.0,Customer_97,26.000000,male,Bhaktapur,200000.0,2200.0,Gold,2024-04-13,2025-10-12,customer97@gmail.com,9.887150e+09,5.0,eSewa
97,1098.0,Customer_98,22.000000,FEMALE,Bhaktapur,55000.0,1200.0,Bronze,2024-11-25,2025-12-02,customer98@gmail.com,9.891391e+09,NaN,eSewa
98,1099.0,Customer_99,24.000000,female,Lalitpur,50000.0,NaN,Gold,2024-10-09,2025-11-25,customer99@gmail.com,9.898474e+09,4.0,Cash
99,1100.0,Customer_100,25.835294,FEMALE,Kathmandu,55000.0,2200.0,Gold,2024-10-12,2025-12-05,customer100@gmail.com,9.822097e+09,5.0,eSewa
Salary,NaN,NaN,NaN,NaN,NaN,55000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Fill Missing City with Mode

In [18]:
df.loc[:, "City"] = df["City"].fillna(df["City"].mode()[0])
df

,Customer_ID,Name,Age,Gender,City,Salary,Purchase_Amount,Membership_Type,Join_Date,Last_Purchase_Date,Email,Phone,Satisfaction_Score,Payment_Method
0,1001.0,Customer_1,25.835294,Male,Kathmandu,55000.0,1800.0,Gold,2024-04-05,2025-12-04,customer1@gmail.com,9.883198e+09,3.0,Bank Transfer
1,1002.0,Customer_2,22.000000,Male,Kathmandu,50000.0,1500.0,Bronze,2024-10-01,2025-09-07,customer2@gmail.com,9.897226e+09,NaN,Card
2,1003.0,Customer_3,28.000000,female,Lalitpur,200000.0,1200.0,Gold,2024-12-14,2025-06-09,customer3@gmail.com,9.830868e+09,4.0,eSewa
3,1004.0,Customer_4,22.000000,Male,Bhaktapur,45000.0,1800.0,Silver,2024-10-09,2025-01-24,customer4@gmail.com,9.871663e+09,3.0,Bank Transfer
4,1005.0,Customer_5,22.000000,female,Lalitpur,200000.0,NaN,Bronze,2024-06-19,2025-04-23,customer5@gmail.com,9.819336e+09,3.0,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,1097.0,Customer_97,26.000000,male,Bhaktapur,200000.0,2200.0,Gold,2024-04-13,2025-10-12,customer97@gmail.com,9.887150e+09,5.0,eSewa
97,1098.0,Customer_98,22.000000,FEMALE,Bhaktapur,55000.0,1200.0,Bronze,2024-11-25,2025-12-02,customer98@gmail.com,9.891391e+09,NaN,eSewa
98,1099.0,Customer_99,24.000000,female,Lalitpur,50000.0,NaN,Gold,2024-10-09,2025-11-25,customer99@gmail.com,9.898474e+09,4.0,Cash
99,1100.0,Customer_100,25.835294,FEMALE,Kathmandu,55000.0,2200.0,Gold,2024-10-12,2025-12-05,customer100@gmail.com,9.822097e+09,5.0,eSewa
Salary,NaN,NaN,NaN,NaN,Lalitpur,55000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Fill Missing Purchase Amount with Median

In [20]:
df.loc[:, "Purchase_Amount"] = df["Purchase_Amount"].fillna(df["Purchase_Amount"].median())
df

,Customer_ID,Name,Age,Gender,City,Salary,Purchase_Amount,Membership_Type,Join_Date,Last_Purchase_Date,Email,Phone,Satisfaction_Score,Payment_Method
0,1001.0,Customer_1,25.835294,Male,Kathmandu,55000.0,1800.0,Gold,2024-04-05,2025-12-04,customer1@gmail.com,9.883198e+09,3.0,Bank Transfer
1,1002.0,Customer_2,22.000000,Male,Kathmandu,50000.0,1500.0,Bronze,2024-10-01,2025-09-07,customer2@gmail.com,9.897226e+09,NaN,Card
2,1003.0,Customer_3,28.000000,female,Lalitpur,200000.0,1200.0,Gold,2024-12-14,2025-06-09,customer3@gmail.com,9.830868e+09,4.0,eSewa
3,1004.0,Customer_4,22.000000,Male,Bhaktapur,45000.0,1800.0,Silver,2024-10-09,2025-01-24,customer4@gmail.com,9.871663e+09,3.0,Bank Transfer
4,1005.0,Customer_5,22.000000,female,Lalitpur,200000.0,1800.0,Bronze,2024-06-19,2025-04-23,customer5@gmail.com,9.819336e+09,3.0,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,1097.0,Customer_97,26.000000,male,Bhaktapur,200000.0,2200.0,Gold,2024-04-13,2025-10-12,customer97@gmail.com,9.887150e+09,5.0,eSewa
97,1098.0,Customer_98,22.000000,FEMALE,Bhaktapur,55000.0,1200.0,Bronze,2024-11-25,2025-12-02,customer98@gmail.com,9.891391e+09,NaN,eSewa
98,1099.0,Customer_99,24.000000,female,Lalitpur,50000.0,1800.0,Gold,2024-10-09,2025-11-25,customer99@gmail.com,9.898474e+09,4.0,Cash
99,1100.0,Customer_100,25.835294,FEMALE,Kathmandu,55000.0,2200.0,Gold,2024-10-12,2025-12-05,customer100@gmail.com,9.822097e+09,5.0,eSewa
Salary,NaN,NaN,NaN,NaN,Lalitpur,55000.0,1800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Check Missing Values Again

In [22]:
df.isnull().sum()

Customer_ID            1
Name                   1
Age                    1
Gender                 1
City                   0
Salary                 0
Purchase_Amount        0
Membership_Type        1
Join_Date              1
Last_Purchase_Date     1
Email                  1
Phone                  1
Satisfaction_Score    26
Payment_Method         1
dtype: int64

### Save Cleaned Dataset

In [23]:
df.to_csv("cleaned_customer_data.csv", index=False)

### Final Cleaned Dataset

In [24]:
df

,Customer_ID,Name,Age,Gender,City,Salary,Purchase_Amount,Membership_Type,Join_Date,Last_Purchase_Date,Email,Phone,Satisfaction_Score,Payment_Method
0,1001.0,Customer_1,25.835294,Male,Kathmandu,55000.0,1800.0,Gold,2024-04-05,2025-12-04,customer1@gmail.com,9.883198e+09,3.0,Bank Transfer
1,1002.0,Customer_2,22.000000,Male,Kathmandu,50000.0,1500.0,Bronze,2024-10-01,2025-09-07,customer2@gmail.com,9.897226e+09,NaN,Card
2,1003.0,Customer_3,28.000000,female,Lalitpur,200000.0,1200.0,Gold,2024-12-14,2025-06-09,customer3@gmail.com,9.830868e+09,4.0,eSewa
3,1004.0,Customer_4,22.000000,Male,Bhaktapur,45000.0,1800.0,Silver,2024-10-09,2025-01-24,customer4@gmail.com,9.871663e+09,3.0,Bank Transfer
4,1005.0,Customer_5,22.000000,female,Lalitpur,200000.0,1800.0,Bronze,2024-06-19,2025-04-23,customer5@gmail.com,9.819336e+09,3.0,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,1097.0,Customer_97,26.000000,male,Bhaktapur,200000.0,2200.0,Gold,2024-04-13,2025-10-12,customer97@gmail.com,9.887150e+09,5.0,eSewa
97,1098.0,Customer_98,22.000000,FEMALE,Bhaktapur,55000.0,1200.0,Bronze,2024-11-25,2025-12-02,customer98@gmail.com,9.891391e+09,NaN,eSewa
98,1099.0,Customer_99,24.000000,female,Lalitpur,50000.0,1800.0,Gold,2024-10-09,2025-11-25,customer99@gmail.com,9.898474e+09,4.0,Cash
99,1100.0,Customer_100,25.835294,FEMALE,Kathmandu,55000.0,2200.0,Gold,2024-10-12,2025-12-05,customer100@gmail.com,9.822097e+09,5.0,eSewa
Salary,NaN,NaN,NaN,NaN,Lalitpur,55000.0,1800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Insights
- Missing values were found in Age, City, Salary, and Purchase Amount columns.
- Age was filled using mean value.
- Salary and Purchase Amount were filled using median value.
- City was filled using mode value.
- Duplicate records were checked and removed.
- Final cleaned dataset is ready for analysis.

## Conclusion
In this assignment, I cleaned a customer dataset using Pandas. I identified missing values, checked duplicate records, removed duplicates, and filled missing values using mean, median, and mode techniques. This task helped me understand real-world data cleaning and preprocessing steps required before data analysis.