## Select rows/columns + Filtering data.

In [1]:
import pandas as pd

### Create Dataset

In [2]:
import pandas as pd

data = {
    "Name": ["Ram", "Hari", "Sita", "Gita", "Shyam"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [80, 75, 90, 65, 55],
    "Department": ["CS", "IT", "CS", "BCA", "IT"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks Department
0    Ram   20     80         CS
1   Hari   21     75         IT
2   Sita   19     90         CS
3   Gita   22     65        BCA
4  Shyam   20     55         IT

### Select Columns

#### Name column

In [3]:
df["Name"]

0      Ram
1     Hari
2     Sita
3     Gita
4    Shyam
Name: Name, dtype: object

#### Marks column

In [5]:
df["Marks"]

0    80
1    75
2    90
3    65
4    55
Name: Marks, dtype: int64

#### multiple columns

In [6]:
df[["Name", "Marks"]]

    Name  Marks
0    Ram     80
1   Hari     75
2   Sita     90
3   Gita     65
4  Shyam     55

### Select Rows

#### Select first row

In [7]:
df.iloc[0]
# iloc means select using row number/index.

Name          Ram
Age            20
Marks          80
Department     CS
Name: 0, dtype: object

#### Select third row

In [8]:
df.iloc[2]

Name          Sita
Age             19
Marks           90
Department      CS
Name: 2, dtype: object

#### Select multiple rows

In [9]:
df.iloc[0:3]

   Name  Age  Marks Department
0   Ram   20     80         CS
1  Hari   21     75         IT
2  Sita   19     90         CS

### Select Specific Row + Column

#### Get value at row 1 and column 2.

In [10]:
df.iloc[1, 2]

75

### Filtering Data

#### Students with marks > 70

In [11]:
df[df["Marks"] > 70]

   Name  Age  Marks Department
0   Ram   20     80         CS
1  Hari   21     75         IT
2  Sita   19     90         CS

#### Students with marks < 60

In [12]:
df[df["Marks"] < 60]

    Name  Age  Marks Department
4  Shyam   20     55         IT

#### Students from CS Department

In [13]:
df[df["Department"] == "CS"]

   Name  Age  Marks Department
0   Ram   20     80         CS
2  Sita   19     90         CS

#### Students with age > 20

In [15]:
df[df["Age"] > 20]

   Name  Age  Marks Department
1  Hari   21     75         IT
3  Gita   22     65        BCA

### Multiple Conditions

##### Students with:
##### Marks > 70
##### AND
##### Department = CS

In [16]:
df[(df["Marks"] > 70) & (df["Department"] == "CS")]

   Name  Age  Marks Department
0   Ram   20     80         CS
2  Sita   19     90         CS

#### Marks > 85 OR Age < 20

In [17]:
df[(df["Marks"] > 85) | (df["Age"] < 20)]

   Name  Age  Marks Department
2  Sita   19     90         CS

## Full Practice Code

In [19]:
import pandas as pd

data = {
    "Name": ["Ram", "Hari", "Sita", "Gita", "Shyam"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [80, 75, 90, 65, 55],
    "Department": ["CS", "IT", "CS", "BCA", "IT"]
}

df = pd.DataFrame(data)

print("Full Dataset:")
print(df)

print("\nSelect Name Column:")
print(df["Name"])

print("\nSelect Name and Marks:")
print(df[["Name", "Marks"]])

print("\nFirst Row:")
print(df.iloc[0])

print("\nRows 0 to 2:")
print(df.iloc[0:3])

print("\nStudents with Marks > 70:")
print(df[df["Marks"] > 70])

print("\nStudents from CS Department:")
print(df[df["Department"] == "CS"])

print("\nMultiple Conditions:")
print(df[(df["Marks"] > 70) & (df["Department"] == "CS")])

Full Dataset:
    Name  Age  Marks Department
0    Ram   20     80         CS
1   Hari   21     75         IT
2   Sita   19     90         CS
3   Gita   22     65        BCA
4  Shyam   20     55         IT

Select Name Column:
0      Ram
1     Hari
2     Sita
3     Gita
4    Shyam
Name: Name, dtype: object

Select Name and Marks:
    Name  Marks
0    Ram     80
1   Hari     75
2   Sita     90
3   Gita     65
4  Shyam     55

First Row:
Name          Ram
Age            20
Marks          80
Department     CS
Name: 0, dtype: object

Rows 0 to 2:
   Name  Age  Marks Department
0   Ram   20     80         CS
1  Hari   21     75         IT
2  Sita   19     90         CS

Students with Marks > 70:
   Name  Age  Marks Department
0   Ram   20     80         CS
1  Hari   21     75         IT
2  Sita   19     90         CS

Students from CS Department:
   Name  Age  Marks Department
0   Ram   20     80         CS
2  Sita   19     90         CS

Multiple Conditions:
   Name  Age  Marks Department
0   Ram   20     80         CS
2  Sita   19     90         CS