# Week 6 Day 3: Handle Outliers

---
## Internship Details

**Intern Name:** Dinesh Singh Dhami  
**Semester:** BE Computer 8th Semester  
**Company:** Sipalaya Info Tech, Kathmandu-32, Koteshwor  
**Domain:** Data Science  
**Task:** Handle Outliers  
**Tools Used:** Python, Pandas, NumPy, Jupyter Notebook  

---

## Objective

The objective of this task is to handle outliers in datasets using different techniques such as removal and capping. Handling outliers improves data quality and ensures better analysis and machine learning model performance.

### Import Libraries

In [1]:
import pandas as pd
import numpy as np

### Load Dataset

In [2]:
df = pd.read_csv("handle_outliers_dataset.csv")
df.head()

   Employee_ID        Name Department  Salary  Experience_Years
0         2001  Employee_1    Finance   42000                 7
1         2002  Employee_2         HR   45000                 1
2         2003  Employee_3      Sales   47000                10
3         2004  Employee_4         IT   48000                 2
4         2005  Employee_5         IT   50000                 4

### Check Dataset Information

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       20 non-null     int64
 1   Name              20 non-null     object
 2   Department        20 non-null     object
 3   Salary            20 non-null     int64
 4   Experience_Years  20 non-null     int64
dtypes: int64(3), object(2)
memory usage: 928.0+ bytes

In [4]:
df.shape

(20, 5)

### View Salary Statistics

In [5]:
df["Salary"].describe()

count        20.000000
mean      79850.000000
std       67647.130098
min       25000.000000
25%       47750.000000
50%       57000.000000
75%       66500.000000
max      260000.000000
Name: Salary, dtype: float64

### Calculate Q1, Q3, and IQR

In [6]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 47750.0
Q3: 66500.0
IQR: 18750.0

### Calculate Lower and Upper Bound

In [7]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Lower Bound: 19625.0
Upper Bound: 94625.0

### Detect Outliers

In [9]:
outliers = df[(df["Salary"] < lower_bound) | (df["Salary"] > upper_bound)]
outliers

    Employee_ID         Name Department  Salary  Experience_Years
15         2016  Employee_16      Sales  210000                 9
16         2017  Employee_17         IT  230000                 3
18         2019  Employee_19         IT  260000                 7

### Count Outliers

In [10]:
print("Total Outliers:", len(outliers))

Total Outliers: 3

### Method 1 - Remove Outliers

In [11]:
df_removed = df[(df["Salary"] >= lower_bound) & (df["Salary"] <= upper_bound)]
df_removed

    Employee_ID         Name Department  Salary  Experience_Years
0          2001   Employee_1    Finance   42000                 7
1          2002   Employee_2         HR   45000                 1
2          2003   Employee_3      Sales   47000                10
3          2004   Employee_4         IT   48000                 2
4          2005   Employee_5         IT   50000                 4
5          2006   Employee_6  Marketing   52000                11
6          2007   Employee_7         IT   54000                11
7          2008   Employee_8    Finance   56000                10
8          2009   Employee_9  Marketing   58000                 1
9          2010  Employee_10         IT   60000                10
10         2011  Employee_11  Marketing   62000                10
11         2012  Employee_12         HR   64000                 7
12         2013  Employee_13         IT   66000                 1
13         2014  Employee_14         IT   68000                 4
14         2015  Employee_15      Sales   70000                 1
17         2018  Employee_18         HR   25000                 5
19         2020  Employee_20  Marketing   30000                 3

### Compare Shape Before and After Removing

In [12]:
print("Original Dataset Shape:", df.shape)
print("After Removing Outliers:", df_removed.shape)

Original Dataset Shape: (20, 5)
After Removing Outliers: (17, 5)

### Method 2 - Cap Outliers

In [14]:
df_capped = df.copy()

df_capped["Salary"] = np.where(
    df_capped["Salary"] > upper_bound,
    upper_bound,
    df_capped["Salary"]
)

df_capped["Salary"] = np.where(
    df_capped["Salary"] < lower_bound,
    lower_bound,
    df_capped["Salary"]
)

df_capped

    Employee_ID         Name Department   Salary  Experience_Years
0          2001   Employee_1    Finance  42000.0                 7
1          2002   Employee_2         HR  45000.0                 1
2          2003   Employee_3      Sales  47000.0                10
3          2004   Employee_4         IT  48000.0                 2
4          2005   Employee_5         IT  50000.0                 4
5          2006   Employee_6  Marketing  52000.0                11
6          2007   Employee_7         IT  54000.0                11
7          2008   Employee_8    Finance  56000.0                10
8          2009   Employee_9  Marketing  58000.0                 1
9          2010  Employee_10         IT  60000.0                10
10         2011  Employee_11  Marketing  62000.0                10
11         2012  Employee_12         HR  64000.0                 7
12         2013  Employee_13         IT  66000.0                 1
13         2014  Employee_14         IT  68000.0                 4
14         2015  Employee_15      Sales  70000.0                 1
15         2016  Employee_16      Sales  94625.0                 9
16         2017  Employee_17         IT  94625.0                 3
17         2018  Employee_18         HR  25000.0                 5
18         2019  Employee_19         IT  94625.0                 7
19         2020  Employee_20  Marketing  30000.0                 3

### Compare Original and Capped Salary

In [15]:
comparison = pd.DataFrame({
    "Original_Salary": df["Salary"],
    "Capped_Salary": df_capped["Salary"]
})

comparison

    Original_Salary  Capped_Salary
0             42000        42000.0
1             45000        45000.0
2             47000        47000.0
3             48000        48000.0
4             50000        50000.0
5             52000        52000.0
6             54000        54000.0
7             56000        56000.0
8             58000        58000.0
9             60000        60000.0
10            62000        62000.0
11            64000        64000.0
12            66000        66000.0
13            68000        68000.0
14            70000        70000.0
15           210000        94625.0
16           230000        94625.0
17            25000        25000.0
18           260000        94625.0
19            30000        30000.0

### Check Salary Statistics After Capping

In [16]:
df_capped["Salary"].describe()

count       20.000000
mean     59043.750000
std      19201.677002
min      25000.000000
25%      47750.000000
50%      57000.000000
75%      66500.000000
max      94625.000000
Name: Salary, dtype: float64

### Save Cleaned Dataset

In [17]:
df_capped.to_csv("handled_outliers_dataset.csv", index=False)

## Conclusion

In this task, I learned how to handle outliers using IQR-based techniques. First, outliers were detected from the Salary column using lower and upper bounds. Then, outliers were handled using two methods: removing outlier records and capping extreme values. Capping was useful because it preserved all records while reducing the effect of abnormal values.