## Sorting + Grouping in Pandas.

In [1]:
import pandas as pd

### Create Dataset

In [2]:
import pandas as pd

data = {
    "Name": ["Ram", "Hari", "Sita", "Gita", "Shyam"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [80, 75, 90, 65, 55],
    "Department": ["CS", "IT", "CS", "BCA", "IT"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks Department
0    Ram   20     80         CS
1   Hari   21     75         IT
2   Sita   19     90         CS
3   Gita   22     65        BCA
4  Shyam   20     55         IT

## Sorting

#### Sort by Marks (Ascending)

In [3]:
df.sort_values(by="Marks")

    Name  Age  Marks Department
4  Shyam   20     55         IT
3   Gita   22     65        BCA
1   Hari   21     75         IT
0    Ram   20     80         CS
2   Sita   19     90         CS

#### Sort by Marks (Descending)

In [4]:
df.sort_values(by="Marks", ascending=False)

    Name  Age  Marks Department
2   Sita   19     90         CS
0    Ram   20     80         CS
1   Hari   21     75         IT
3   Gita   22     65        BCA
4  Shyam   20     55         IT

#### Sort by Age

In [5]:
df.sort_values(by="Age")

    Name  Age  Marks Department
2   Sita   19     90         CS
0    Ram   20     80         CS
4  Shyam   20     55         IT
1   Hari   21     75         IT
3   Gita   22     65        BCA

### Sort by Multiple Columns

##### Sort by:
##### Department
##### Marks

In [7]:
df.sort_values(by=["Department", "Marks"])

    Name  Age  Marks Department
3   Gita   22     65        BCA
0    Ram   20     80         CS
2   Sita   19     90         CS
4  Shyam   20     55         IT
1   Hari   21     75         IT

## Grouping

#### Group by Department

In [8]:
df.groupby("Department")

#### Count students in each department

In [9]:
df.groupby("Department").size()

Department
BCA    1
CS     2
IT     2
dtype: int64

#### Average marks by department

In [10]:
df.groupby("Department")["Marks"].mean()

Department
BCA    65.0
CS     85.0
IT     65.0
Name: Marks, dtype: float64

#### Maximum marks by department

In [11]:
df.groupby("Department")["Marks"].max()

Department
BCA    65
CS     90
IT     75
Name: Marks, dtype: int64

#### Minimum marks by department

In [12]:
df.groupby("Department")["Marks"].min()

Department
BCA    65
CS     80
IT     55
Name: Marks, dtype: int64

#### Sum of marks by department

In [14]:
df.groupby("Department")["Marks"].sum()

Department
BCA     65
CS     170
IT     130
Name: Marks, dtype: int64

## Full Practice Code

In [15]:
import pandas as pd

data = {
    "Name": ["Ram", "Hari", "Sita", "Gita", "Shyam"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [80, 75, 90, 65, 55],
    "Department": ["CS", "IT", "CS", "BCA", "IT"]
}

df = pd.DataFrame(data)

print("Original Dataset:")
print(df)

print("\nSorted by Marks Ascending:")
print(df.sort_values(by="Marks"))

print("\nSorted by Marks Descending:")
print(df.sort_values(by="Marks", ascending=False))

print("\nSorted by Age:")
print(df.sort_values(by="Age"))

print("\nStudents Count by Department:")
print(df.groupby("Department").size())

print("\nAverage Marks by Department:")
print(df.groupby("Department")["Marks"].mean())

print("\nMaximum Marks by Department:")
print(df.groupby("Department")["Marks"].max())

Original Dataset:
    Name  Age  Marks Department
0    Ram   20     80         CS
1   Hari   21     75         IT
2   Sita   19     90         CS
3   Gita   22     65        BCA
4  Shyam   20     55         IT

Sorted by Marks Ascending:
    Name  Age  Marks Department
4  Shyam   20     55         IT
3   Gita   22     65        BCA
1   Hari   21     75         IT
0    Ram   20     80         CS
2   Sita   19     90         CS

Sorted by Marks Descending:
    Name  Age  Marks Department
2   Sita   19     90         CS
0    Ram   20     80         CS
1   Hari   21     75         IT
3   Gita   22     65        BCA
4  Shyam   20     55         IT

Sorted by Age:
    Name  Age  Marks Department
2   Sita   19     90         CS
0    Ram   20     80         CS
4  Shyam   20     55         IT
1   Hari   21     75         IT
3   Gita   22     65        BCA

Students Count by Department:
Department
BCA    1
CS     2
IT     2
dtype: int64

Average Marks by Department:
Department
BCA    65.0
CS     85.0
IT     65.0
Name: Marks, dtype: float64

Maximum Marks by Department:
Department
BCA    65
CS     90
IT     75
Name: Marks, dtype: int64